version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://user:password@db/dbname
      - SECRET_KEY=your_secret_key
      - LINKEDIN_CLIENT_ID=your_linkedin_client_id
      - LINKEDIN_CLIENT_SECRET=your_linkedin_client_secret
    ports:
      - "5000:5000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: postgres:13
    container_name: db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dbname
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
